name: Emoji Scan

on:
  push:
  pull_request:

jobs:
  scan:
    name: Check for emojis in repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install rich

      - name: Run emoji scan
        run: |
          . .venv/bin/activate
            python .github/workflows/scripts/emoji_scan.py